version: "3.9"

services:
  neo4j-main:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j-main
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/qweasd312qwe
