version: "3.7"
services:
  tiktok-gateway:
    image: 450680964076.dkr.ecr.ap-southeast-1.amazonaws.com/tiktok-gateway:0.0.0
    networks:
      - cluster
    command: /go/bin/tiktok-gateway
    env_file:
      - ./tiktok.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 5s
networks:
  cluster:
    driver: overlay
    attachable: true
