version: "3.9"

services:
  prometheus-main:
    image: prom/prometheus
    container_name: prometheus-main
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
# networks:
#   monitoring:
#     name: monitoring-main
#     driver: bridge
#     external: true
volumes:
  prometheus-data:
    name: prometheus-data
    driver: local
