version: "3.8"

services:
    mosquitto-default:
        image: eclipse-mosquitto:latest
        container_name: mosquitto_default
        hostname: mosquitto_default
        ports:
            - "9001:9001"
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - /mosquitto/data
            - /mosquitto/log
