version: '3'

services:
    rabbit-main:
        image: rabbitmq:3.10.5-management-alpine
        hostname: rabbit-main
        container_name: rabbit-main
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
        networks:
            - main-network

networks:
    main-network:
        name: main-network
        driver: brigde
        external: true
