version: "3"

services:
  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    hostname: cadvisor
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run/:/var/run/:rw
      - /sys:/sys:ro
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true
    # networks:
    #   - monitoring
networks:
  monitoring:
    name: monitoring-main
    driver: bridge
    external: true
