version: '3.7'

services:
    db:
        image: 'postgres:14-alpine'
        container_name: postgres_general
        environment:
            - 'POSTGRES_USER=${DB_USER}'
            - 'POSTGRES_PASSWORD=${DB_PASS}'
            - 'POSTGRES_DB=${DB_NAME}'
        restart: always
        ports:
            - '5432:5432'
